#  Data Cleaning & Preprocessing Project

##  Problem Statement

Real-world datasets are often messy, containing inconsistencies, missing values, incorrect formats, and structural issues.
The goal of this project is to clean and preprocess a messy IMDB dataset and transform it into a structured, analysis-ready dataset.

---

##  Objectives

* Identify data quality issues
* Clean and standardize the dataset
* Handle missing values
* Convert data into appropriate formats
* Prepare dataset for further analysis or modeling

## Import libraries

In [52]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

##  Data Loading

The dataset is loaded using pandas. Since the dataset contains encoding and delimiter issues, appropriate parameters are used to correctly parse the file.

In [5]:
df = pd.read_csv(
    r"C:\Users\akhia\Documents\IBM_data_cleaning\data\messy_IMDB_dataset.csv",
    sep=';',
    encoding='latin1'
)
df.head()

,IMBD title ID,Original titlÊ,Release year,Genrë¨,Duration,Country,Content Rating,Director,Unnamed: 8,Income,Votes,Score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

## Data Cleaning

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

In [7]:
df.head()

,imbd_title_id,original_titlê,release_year,genrë¨,duration,country,content_rating,director,unnamed:_8,income,votes,score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

##  Column Name Cleaning

Column names are cleaned to ensure consistency by removing extra spaces, converting to lowercase, and standardizing naming conventions.

In [ ]:
df.rename(columns={'imbd_title_id' : 'imdb_title_id','original_titlê' : 'original_title', 'genrë¨' : 'genre'},inplace=True
)

##  Initial Data Exploration

We begin by inspecting the first few rows of the dataset to understand its structure and identify visible inconsistencies.

In [9]:
df.head()

,imdb_title_id,original_title,release_year,genre,duration,country,content_rating,director,unnamed:_8,income,votes,score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,NaN,$ 28815245,2.278.845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,NaN,$ 246120974,1.572.674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,NaN,$ 1005455211,2.241.615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,NaN,"$ 4o8,035,783",1.098.714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,NaN,$ 222831817,1.780.147,"8,9f"

##  Data Issues Identified

The dataset contains several inconsistencies:

* Incorrect delimiter causing parsing issues
* Encoding problems leading to corrupted text
* Numerical columns containing symbols and invalid characters
* Missing values in multiple columns
* Inconsistent categorical values
* Presence of malformed or empty rows

These issues need to be addressed before performing any analysis.

In [11]:
df.drop(columns=['unnamed:_8'],inplace=True)

In [13]:
df.dropna(how='all', inplace=True)

In [14]:
import numpy as np

df.replace(
    ['Nan', 'NULL', '-', 'Inf', 'Not Applicable', '#N/A', ''],
    np.nan,
    inplace=True
)

In [19]:
df.head()

,imdb_title_id,original_title,release_year,genre,duration,country,content_rating,director,income,votes,score
0,tt0111161,The Shawshank Redemption,1995-02-10,Drama,142,USA,R,Frank Darabont,28815245,2278845,9.3
1,tt0068646,The Godfather,09 21 1972,"Crime, Drama",175,USA,R,Francis Ford Coppola,246120974,1572674,9.2
2,tt0468569,The Dark Knight,23 -07-2008,"Action, Crime, Drama",152,US,PG-13,Christopher Nolan,1005455211,2241615,9.
3,tt0071562,The Godfather: Part II,1975-09-25,"Crime, Drama",220,USA,R,Francis Ford Coppola,48035783,1098714,"9,.0"
4,tt0110912,Pulp Fiction,1994-10-28,"Crime, Drama",,USA,R,Quentin Tarantino,222831817,1780147,"8,9f"

In [16]:
df['income'] = (df['income'].str.replace('$','' , regex=False).str.replace(',' , '' , regex=False).str.replace('o', '',regex=False).str.strip())

df['income'] = pd.to_numeric(df['income'], errors='coerce')

In [17]:
df['votes'] = df['votes'].str.replace('.', '' , regex=False).str.strip()
df['votes'] = pd.to_numeric(df['votes'], errors='coerce')

In [20]:
df['score'] = (
    df['score']
    .str.replace(',', '.', regex=False)
    .str.replace('f', '', regex=False)
    .str.replace('..', '.', regex=False)
    .str.strip()
)

df['score'] = pd.to_numeric(df['score'], errors='coerce')

In [21]:
df['duration'] = pd.to_numeric(df['duration'], errors='coerce')

In [26]:
df['country'] = df['country'].str.replace('.','',regex=False).str.strip()

df['country'] = df['country'].replace({
    'US': 'USA',
    'US.': 'USA'
})

In [27]:
df['genre'] = df['genre'].str.replace('\t', ',', regex=True)
df['genre'] = df['genre'].str.strip()

In [28]:
df['release_year'] = pd.to_datetime(df['release_year'], errors='coerce')

##  Dataset Overview

We analyze the dataset structure, data types, and summary statistics to identify potential issues such as incorrect data types and missing values.

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100 entries, 0 to 100
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   imdb_title_id   100 non-null    object
 1   original_title  100 non-null    object
 2   release_year    89 non-null     datetime64[ns]
 3   genre           100 non-null    object
 4   duration        93 non-null     float64
 5   country         100 non-null    object
 6   content_rating  77 non-null     object
 7   director        100 non-null    object
 8   income          100 non-null    int64
 9   votes           100 non-null    int64
 10  score           97 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(2), object(6)
memory usage: 9.4+ KB

In [30]:
df.isnull().sum()

imdb_title_id      0
original_title     0
release_year      11
genre              0
duration           7
country            0
content_rating    23
director           0
income             0
votes              0
score              3
dtype: int64

In [32]:
df = df.dropna(subset=['release_year'])

##  Handling Missing Values

Missing values are handled using appropriate strategies:

* Numerical columns → filled using median
* Categorical columns → filled with placeholder values
* Critical fields → rows removed where necessary

In [34]:
df['duration'].fillna(df['duration'].median(), inplace=True)

C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\47760748.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['duration'].fillna(df['duration'].median(), inplace=True)
C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\47760748.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['duration'].fillna(df['duration'].median(), inplace=True)

In [37]:
df['score'].fillna(df['score'].median(), inplace=True)

C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\2986341347.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['score'].fillna(df['score'].median(), inplace=True)
C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\2986341347.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['score'].fillna(df['score'].median(), inplace=True)

##  Categorical Data Standardization

Categorical columns contain inconsistent labels due to typos and formatting differences.
These values are standardized to ensure uniform representation across the dataset.

In [36]:
df['content_rating'].fillna('Unknown', inplace=True)

C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\2945097902.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['content_rating'].fillna('Unknown', inplace=True)
C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\2945097902.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content_rating'].fillna('Unknown', inplace=True)

In [38]:
df.isnull().sum()

imdb_title_id     0
original_title    0
release_year      0
genre             0
duration          0
country           0
content_rating    0
director          0
income            0
votes             0
score             0
dtype: int64

##  Statistical Summary

We analyze the cleaned dataset to understand distributions, detect skewness, and verify that values are within expected ranges.

In [40]:
df.describe()

,release_year,duration,income,votes,score
count,89,89.000000,8.900000e+01,8.900000e+01,89.000000
mean,1991-08-26 07:00:40.449438208,132.792135,2.907064e+08,7.933418e+05,8.191011
min,1937-03-12 00:00:00,81.000000,5.760000e+02,1.973810e+05,7.400000
25%,1980-09-19 00:00:00,115.000000,2.334157e+07,3.628970e+05,7.900000
50%,1995-12-01 00:00:00,127.500000,1.096763e+08,7.482910e+05,8.200000
75%,2006-10-27 00:00:00,148.000000,3.901332e+08,1.049009e+06,8.500000
max,2020-01-23 00:00:00,229.000000,2.797801e+09,2.278845e+06,9.300000
std,NaN,29.593535,4.366105e+08,4.513289e+05,0.425238

# Handling inconsistent values

In [41]:
df.duplicated().sum()

np.int64(0)

In [43]:
df['country'].unique()

array(['USA', 'New Zesland', 'Brazil', 'Japan', 'Italy1', 'South Korea',
       'UK', 'France', 'Italy', 'Germany', 'India', 'Denmark',
       'West Germany', 'Iran'], dtype=object)

In [44]:
df['content_rating'].unique()

array(['R', 'Not Rated', 'PG-13', 'PG', 'Unknown', 'Unrated', 'G'],
      dtype=object)

In [48]:
df['country'] = df['country'].str.strip()

df['country'] = df['country'].replace({
    'New Zesland': 'New Zealand',
    'Italy1': 'Italy',
    'UK': 'United Kingdom',
    'West Germany': 'Germany'
})

C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\884830918.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'] = df['country'].str.strip()
C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\884830918.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['country'] = df['country'].replace({

In [49]:
df['content_rating'] = df['content_rating'].replace({
    'Not Rated': 'Unrated'
})

C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\4188888105.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['content_rating'] = df['content_rating'].replace({

In [50]:
df['country'].unique()

array(['USA', 'New Zealand', 'Brazil', 'Japan', 'Italy', 'South Korea',
       'United Kingdom', 'France', 'Germany', 'India', 'Denmark', 'Iran'],
      dtype=object)

In [51]:
df['content_rating'].unique()

array(['R', 'Unrated', 'PG-13', 'PG', 'Unknown', 'G'], dtype=object)

# Handling outliers

In [45]:
import numpy as np
df['income_log'] = np.log1p(df['income'])

C:\Users\akhia\AppData\Local\Temp\ipykernel_19328\569723773.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['income_log'] = np.log1p(df['income'])

##  Data Validation

After cleaning, the dataset is validated to ensure:

* No missing values remain
* No duplicate rows exist
* Data types are correctly assigned

In [53]:
df.to_csv("cleaned_imdb_dataset.csv", index=False)

##  Export Cleaned Dataset

The cleaned dataset is saved for further analysis and modeling.

##  Conclusion

The dataset was transformed from a highly inconsistent and messy format into a clean and structured dataset.

Key achievements:

* Fixed delimiter and encoding issues
* Cleaned and standardized numerical and categorical data
* Handled missing values effectively
* Ensured data consistency and integrity

The dataset is now ready for exploratory data analysis and machine learning tasks.